name: 发布并推送到Telegram

on:
  release:
    types: [published]

jobs:
  notify:
    name: 发布信息推送到Telegram
    runs-on: ubuntu-latest
    steps:
      - name: 发送Telegram通知
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            <p>${{ github.event.release.tag_name }}</p>
            <p>更新内容:</p>
            <p>${{ github.event.release.body }}</p>
            <p>压缩包下载:</p>
            <p><a href="${{ github.event.release.html_url }}">${{ github.event.release.html_url }}</a></p>
            <p>Docker: </p>
            <p><a href="https://github.com/setube/stb/pkgs/container/stb">https://github.com/setube/stb/pkgs/container/stb</a></p>
