name: 发布Telegram通知

on:
  release:
    types: [published]

jobs:
  build:
    name: 构建源码包
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 创建源码压缩包
        run: |
          git archive --format=zip --output=source.zip HEAD

      - name: 上传源码包
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./source.zip
          asset_name: source.zip
          asset_content_type: application/zip

  notify:
    name: 发送通知
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 发送 Telegram 通知
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            <code>${{ github.event.release.tag_name }}</code>
            <pre>${{ github.event.release.body }}</pre>
