name: 发布并推送到Telegram

on:
  release:
    types: [published]

jobs:
  build:
    name: 构建并上传源码包
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 创建源码压缩包
        run: |
          git archive --format=zip --output=${{ github.event.release.tag_name }}.zip HEAD

      - name: 上传源码包到Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.release.tag_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: artifact-*
          merge-multiple: true

      - name: Push to telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TAG: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python release_telegram.py
    