name: 发布并推送到Telegram

on:
  release:
    types: [published]

jobs:
  telegram_notification:
    name: 处理Telegram通知
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 创建 dist 目录
        run: mkdir -p dist

      - name: 生成源码归档文件到 dist 目录
        run: |
          git archive --format=zip --output=source.zip HEAD
          mv source.zip "dist/Source code (zip)"
          git archive --format=tar.gz --output=source.tar.gz HEAD
          mv source.tar.gz "dist/Source code (tar.gz)"

      - name: 安装 Python 依赖并运行脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TAG: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python release_telegram.py
